CROSYS_TEST/Models/Search.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel;
using CROSYS_TEST.Models.support;
using System.Web.Mvc;

namespace CROSYS_TEST.Models
{

    public class Search : IDataErrorInfo
    {
        //public SelectListItem[] Structure { get; set; }

        public string SearchField { get; set; }
        public string SearchRequest { get; set; }
        public string SearchType { get; set; }

        public string[] Fields { get; set; }
        public Record[] SearchResult { get;private set; }

        public string Error { get { return null; } }

        public Search() {
            //getFields();
            SearchType = "like";
            SearchField = getFields()[0].Value;
        }

        public SelectListItem[] getFields()
        {
         CSVLoader fields = new CSVLoader( AppDomain.CurrentDomain.BaseDirectory + @"/data/structure.csv");

         SelectListItem[] Struc = new SelectListItem[fields.Records.Count];
            int i = 0;
            foreach (Record field in fields.Records)
            {
                Struc[i++] = new SelectListItem { Text = field[fields.Fields[2]], Value = field[fields.Fields[0]] };
            }
            Struc[0].Selected = true;

            return Struc;
        }

    #region Поиск
    //Реализуется два типа поиска - по вхождению и по точному совпадению
    //для начала загрузим CSV файл в ассоциативный массив
    public void search()
    {
        Validation();
            CSVLoader data = new CSVLoader(AppDomain.CurrentDomain.BaseDirectory + @"/data/data.csv");
            Fields = data.Fields;
            if (SearchType == "exact") //точный поиск
            {
                var res = from Result in data.Records
                          where Result[SearchField] == SearchRequest
                          select Result;

                SearchResult = res.ToArray();
            }
            if (SearchType == "like") //поиск "содержит"
            {
                var res = from Result in data.Records
                          where Result[SearchField].Contains(SearchRequest)
                          select Result;

                SearchResult = res.ToArray();
            }
    }

#endregion
    #region Валидация данных
        public string this[string property]
        {
            get
            {
                if ((property == "SearchField")   && string.IsNullOrEmpty(SearchField))   return "Введите поле для поиска";
                if ((property == "SearchType")    && string.IsNullOrEmpty(SearchType))    return "Введите тип поиска";
                if ((property == "SearchRequest") && string.IsNullOrEmpty(SearchRequest)) return "Введите текст для поиска";
                
                return null;
            }
        }
        private void Validation()
        {
            var Validator = new[] { "SearchField", "SearchRequest", "SearchType" };
            bool isValid = Validator.All(x => this[x] == null);
            if (!isValid)
                throw new InvalidOperationException("Неправильный поисковый запрос!");
        }
        #endregion

    }
}

CROSYS_TEST/Controllers/SearchController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CROSYS_TEST.Models;

namespace CROSYS_TEST.Controllers
{
    public class SearchController : Controller
    {
        //
        // GET: /Search/
        [HttpGet]
        public ViewResult Index(Search data)
        {
            ViewData["Fields"] = data.getFields();
            return View("Index",data);
        }

        //
        // POST: /Search/Result
        [HttpPost]
        public ViewResult Result(Search data)//, Fields fields)
        {
            ViewData["Fields"] = data.getFields();
            if (ModelState.IsValid)
            {
                data.search();
                return View("Result", data);
            }
            else 
            {
                return View("Index", data);
            }
        }

    }
}

CROSYS_TEST/Views/Search/Index.cshtml
@{
    ViewBag.Title = "Поиск";
}

<h1>Поиск</h1>

@RenderPage("~/Views/Search/_search_panel.cshtml")

CROSYS_TEST/Views/Search/Result.cshtml
@model CROSYS_TEST.Models.Search

@{
    ViewBag.Title = "Результат";
}

<h1>Результат</h1>

@RenderPage("~/Views/Search/_search_panel.cshtml")
<a class="open_window" href="#" >отобразить в окне</a><br><br>
<table id="results">
<thead>
<tr>
@foreach (var fieldName in Model.Fields)
{
    <th>@fieldName</th>
}
</tr>
</thead>
<tbody>
@foreach (var row in Model.SearchResult)
{
   <tr>
   @foreach (var fieldName in Model.Fields)
   {
    <td>@row[fieldName]</td>
   }
   </tr>
}
</tbody>
</table>


<div class="overlay" title="окно"></div>
<div class="popup">
<div class="close_window">x</div>
<p>
    <table id="results_pop">
    <thead>
    <tr>
    @foreach (var fieldName in Model.Fields)
    {
        <th>@fieldName</th>
    }
    </tr>
    </thead>
    <tbody>
    @foreach (var row in Model.SearchResult)
    {
       <tr>
       @foreach (var fieldName in Model.Fields)
       {
        <td>@row[fieldName]</td>
       }
       </tr>
    }
    </tbody>
    </table>
</p>
</div>


@section scripts{
<!--@Styles.Render("http://cdn.datatables.net/1.10.7/css/jquery.dataTables.min.css")
@Scripts.Render("http://cdn.datatables.net/1.10.7/js/jquery.dataTables.min.js")
@Styles.Render("~/Content/flexigrid.css")
@Scripts.Render("~/Scripts/flexigrid.js")-->
@Styles.Render("~/Content/jquery.dynatable.css")
@Scripts.Render("~/Scripts/jquery.dynatable.js")
@Scripts.Render("~/Scripts/Result.js")
}

CROSYS_TEST/Views/Search/_search_panel.cshtml
@using(Html.BeginForm("Result","Search",FormMethod.Post)) {
        
       <p>Поиск по полю: @Html.DropDownList("SearchField", (SelectListItem[])ViewData["Fields"])</p>
    
       <p>Тип поиска: @Html.DropDownList("SearchType", new SelectListItem[] { 
                  new SelectListItem { Text = "Содержит", Value = "like", Selected = true },
                  new SelectListItem { Text = "Точное вхождение", Value = "exact", Selected = false }
                                                                              })</p>
       <p>Поиск: @Html.TextBox("SearchRequest")</p>
       
       <input type="submit" value="Поиск" />
}
@Html.ValidationSummary()